//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class KSAudioStreamPlayBackItem, KSNewAudioPlayerManager, KSSongInfo, NSObject, NSString;

@interface KSAudioPlayer : NSObject
{
//    id <KSAudioPlayerUserDefineProtocol> _userProtocol;
    NSObject<OS_dispatch_queue> *_queue;
    KSSongInfo *_curSong;
//    id <KSAudioPlayerDelegate> _delegate;
    BOOL _manualProcessInterrup;
    BOOL _pauseOnHeadPhoneOut;
    float _volume;
    float _playRate;
    BOOL _seekToPlayAuto;
    KSNewAudioPlayerManager *_audioManager;
    KSAudioStreamPlayBackItem *_playerItem;
}

@property(retain) KSAudioStreamPlayBackItem *playerItem; // @synthesize playerItem=_playerItem;
@property(nonatomic) KSNewAudioPlayerManager *audioManager; // @synthesize audioManager=_audioManager;
@property(nonatomic) BOOL seekToPlayAuto; // @synthesize seekToPlayAuto=_seekToPlayAuto;
@property(nonatomic) BOOL pauseOnHeadPhoneOut; // @synthesize pauseOnHeadPhoneOut=_pauseOnHeadPhoneOut;
@property(nonatomic) BOOL manualProcessInterrup; // @synthesize manualProcessInterrup=_manualProcessInterrup;
//@property(nonatomic) __weak id <KSAudioPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *audioQueue; // @synthesize audioQueue=_queue;
//- (void).cxx_destruct;
- (void)audioPlayer:(id)arg1 dataBuffering:(double)arg2;
- (void)audioPlayer:(id)arg1 status:(unsigned long long)arg2 params:(id)arg3;
- (BOOL)isPlayStop;
- (BOOL)isSeeking;
- (BOOL)isPause;
- (BOOL)isRealPlaying;
- (BOOL)isPlaying;
- (id)getAudioProcessor:(id)arg1;
- (BOOL)bAudioSessionActive;
- (BOOL)resumeSync;
- (BOOL)resumeInner:(BOOL)arg1;
- (void)pausePlayAndDownloadData;
- (BOOL)pauseSync;
- (BOOL)pauseInner:(BOOL)arg1;
- (id)createDataProvider:(id)arg1;
- (BOOL)seekSync:(double)arg1;
- (void)seek:(double)arg1;
- (void)resume;
- (void)pause;
- (void)stop;
- (BOOL)play:(id)arg1 seekTime:(double)arg2;
- (BOOL)play:(id)arg1;
@property(nonatomic) float playRate;
@property(nonatomic) float volume;
@property(readonly, nonatomic) KSSongInfo *curSong;
- (unsigned long long)errType;
- (id)errDetail;
- (id)dataProviderDetail;
- (double)firstBufTime;
@property(readonly, nonatomic) double playTimeWithNoPause;
@property(readonly, nonatomic) double curTime;
@property(readonly, nonatomic) unsigned int secondCacheCnt;
@property(readonly, nonatomic) double cacheProgress;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) unsigned long long status;
- (void)dealloc;
- (id)initWithUserProtocol:(id)arg1 queue:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

