//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SceneKit/SceneKit.h>

@class NSColor, NSString, NSTrackingArea, NSView;

__attribute__((visibility("hidden")))
@interface QMHoverTextField : NSTextField
{
    BOOL _isNeedUnderLine;
    BOOL _isNeedHover;
    BOOL _isWrap;
    BOOL _fobidenHandCursor;
    BOOL _MouseAreaRect;
    NSColor *_originColor;
    NSColor *_hoverColor;
    NSColor *_highlightColor;
    NSString *_startFlag;
    NSString *_endFlag;
    double _fontSize;
    NSString *_fontFamily;
    NSTrackingArea *_tracker;
    NSView *_underLineView;
}

@property(retain, nonatomic) NSView *underLineView; // @synthesize underLineView=_underLineView;
@property(retain, nonatomic) NSTrackingArea *tracker; // @synthesize tracker=_tracker;
@property(nonatomic) BOOL MouseAreaRect; // @synthesize MouseAreaRect=_MouseAreaRect;
@property(nonatomic) BOOL fobidenHandCursor; // @synthesize fobidenHandCursor=_fobidenHandCursor;
@property(retain, nonatomic) NSString *fontFamily; // @synthesize fontFamily=_fontFamily;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(retain, nonatomic) NSString *endFlag; // @synthesize endFlag=_endFlag;
@property(retain, nonatomic) NSString *startFlag; // @synthesize startFlag=_startFlag;
@property(retain, nonatomic) NSColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property(nonatomic) BOOL isWrap; // @synthesize isWrap=_isWrap;
@property(nonatomic) BOOL isNeedHover; // @synthesize isNeedHover=_isNeedHover;
@property(nonatomic) BOOL isNeedUnderLine; // @synthesize isNeedUnderLine=_isNeedUnderLine;
@property(retain, nonatomic) NSColor *hoverColor; // @synthesize hoverColor=_hoverColor;
@property(retain, nonatomic) NSColor *originColor; // @synthesize originColor=_originColor;
//- (void).cxx_destruct;
- (void)setOriginState;
- (id)getHighlightAttrbuteString:(id)arg1;
- (void)setHightligtStringValue:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)performAction;
- (void)mouseDown:(id)arg1;
- (void)updateTrackingAreas;
- (void)updateFont;
- (id)initWithFrame:(struct CGRect)arg1;

@end

